name: soliter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  ###
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.2.1
  go_router: ^16.3.0
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  ###
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: w500
      fonts:
        - asset: assets/fonts/Inter-Medium.ttf
    - family: w600
      fonts:
        - asset: assets/fonts/Inter-SemiBold.ttf
    - family: w700
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
